[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 1000000
via_ir = true
ffi = false
gas_reports = ["*"]
gas_limit = 30000000


remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]


# Monad Testnet
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain-id = 10143


[etherscan]
monad-testnet = { key = "", chain = 10143, url = "https://api.monadexplo" }


[rpc_endpoints]
monad-testnet = "https://testnet-rpc.monad.xyz"
monad-mainnet = "https://rpc.monad.xyz"
localhost = "http://localhost:8545"


[fuzz]
runs = 1000000
max_test_rejects = 65536
seed = "0x1337"


[invariant]
runs = 1000
depth = 100
fail_on_revert = true